---
title: "Research Paper"
author: "Jody Holland"
date: "2023-03-31"
fontsize: 11pt
mainfont: Calibri
sansfont: Calibri
monofont: Calibri
output: pdf_document
---

# Abstract

# Introduction

Many island economies are reliant on mass tourism to their coastal areas. Yet, the negative environmental implications of this arrangement may be substantial. In this context, "mass tourism" denotes a economic strategy of maximising the number of visitors to an area, with less focus on targeted marketing to specific types of visitors. A contrasting arrangement may be efforts to tailor a tourism arrangement a small number of high spending wealthy guests, sometimes refereed to "alternative-tourism". Nonetheless, for many islands, mass tourism remains a reliable source of revenue, and any efforts to move beyond the model are costly and potentially could backfire. This was highlighted during 2020-2022 restrictions on international travel during the COVID-19 pandemic. During this period several islands around suffered serious declines in economic output. Thus, when restrictions eased, many islands eagerly accommodated mass tourism, seeing it as low investment, high yield, and reliable model of raising much needed revenue.

Yet, there are significant negative consequences to mass tourism. Mass tourism has been attributed to overcrowding, particularly on coastal areas. As a consequence, locals may be "spaced out" of public areas such as beaches. Furthermore, and more relevant to this study, mass tourism has been linked to increased pollution and environmental degradation. Such damage and pollution may also be more prevalent in coastal areas. This is particularly concerning as the threat of terrestrial pollution such as sunscreen or litter entering fragiles marine environments could endanger populations of several species and disrupt precious ecosystem services. Furthermore, the effect of pollution and litter in spoiling the environment and aesthetic beauty of coastal areas could also lead to tourists being less likely to visit, thus threatening the revenue streams from mass tourism. To this end, there are identifiable costs and benefits to mass tourism for policy makers. Whilst the economic yields may be high, the costs of mass tourism could be significant upon both the local population and environment. Thus, research into the dynamics of how the negative consequences of mass tourism develop could be beneficial for policy makers seeking to mitigate its potentially harmful impacts.

This study seeks to understand how tourist demographics and tourist density relates to the generation of terrestrial litter on beaches, within the context of mass tourism. The term tourist demographics denotes the features that differentiate different groups of tourist. This could entail variables such as national origin, education level, familial status, age, and gender. The concept of tourist density denotes the number and concentration of tourists close to each of our study areas. Finally, the notion of terrestrial litter relates to litter generated by land based activities. This is as opposed to marine litter, which may be brought onto beaches by marine currents.

This study focuses on the island of Fuerteventura in the Canary Islands. The Canary Islands are a leading international tourist location and a center of the mass tourism model, with 12.6 million visits in 2022 alone. The most popular islands for tourism are Tenerife, Gran Canaria, Lanzarote, Fuerteventura. A popular tourist destination, Fuerteventura is renowned for its beaches and coastal areas. Popular beaches include Morro Jable, Costa Calma and El Confital. As a result, there is significant international tourism to Fuerteventura, notably from Northern and Western European countries such as Germany, the United Kingdom, and Sweden. This has formed a significant and important sector within the economy of Fuerteventura. Yet, as a result of this tourism, there may be significant strain upon coastal environments on Fuerteventura as a result of terrestrial tourism activities, particularly in the form of litter such as plastics and foodstuffs. Thus, for policy makers on Fuerteventura, identifying the conditions relating to how this litter is generated may be crucial for guiding an intervention to reduce terrestrial litter on the beaches. As well as tourist demographics and density, other factors could be influencial. For instance, better weather days could increase the frequency of people eating on beaches, and thus increase the level of food packaging within samples of terrestrial litter. Nonetheless, efforts to build a comprehensive model of how conditions effect the generation of terrestrial litter could be a very beneficial toolkit to form part of wider efforts to mitigate the negative consequences of mass tourism on Fuerteventura.

To frame this line of anayslis together into a research question:

*To what extent does tourist demographics and density influence the generation of terrestrial litter on the beaches of Fuerteventura?*
