---
title: "Key Readings Summaries"
author: "Jody Holland"
date: "2023-03-22"
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
bibliography: summaries.bib
nocite: '@*'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Preface

This document is to serve as a selection of summaries of literature that I regard as potentially very related to the research themes in this project.

## [@santos2005]

This paper from 2005 relates to research from Brazil in 2003. Based in the south of Brazil the aim of this research was threefold. The researchers aimed to determine the characteristics of people who engage in littering, as well as the perceptions of people to the problem of litter on the beach. To achieve this they used a mix of qualitative and quantitative methods, including handing out a survey to beach visitors, sampling the characteristics of visitors to the beaches over a period of time, and sampling the level of litter on the beaches over the same period of time. The results indicated that people's primary concern was relating to the dangers to humans caused by littering. They also found that when a beach was visted by increased levels of low-income and low-education people, the levels of litter increased relative to the base line.

In my opinion this research is limited to not exploring if national background caused differentiation in littering behaviour, is quite old
